spring:
  application:
    name: dbpractice

  datasource:
    url: jdbc:postgresql://localhost:5432/dbpractice
    username: app
    password: apppw
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#    url: jdbc:h2:file:./data/appdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  sql:
    init:
      mode: always

app:
  import:
    dir: /Users/choihyeongseok/Desktop/bigData/product

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
