spring:
  application:
    name: dbpractice

  datasource:
    url: jdbc:postgresql://localhost:5432/dbpractice
    username: app
    password: apppw
    driver-class-name: org.postgresql.Driver

#    url: jdbc:h2:file:./data/appdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  sql:
    init:
      mode: always